server:
  port: 9000

spring:
  application:
    name: auth_server

  datasource:
    generate-unique-name: false
    name: auth_server
    url: "jdbc:h2:mem:auth_server"

logging:
  level:
    root: info
    org.springframework.security: info
