spring:
  application:
    name: sinaction
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: "jdbc:h2:mem:tacocloud"

logging:
  level:
    root: info
    org.springframework.security: info

greeting:
  welcome: Welcome to user ${spring.application.name}

taco:
  orders:
    page-size: 20