spring:
  application:
    name: business
  thymeleaf:
    cache: false
  profiles:
    active:
      development
  rabbitmq:
    username: admin
    password: admin
    virtual-host: vhost
    port: 5672
    template:
      exchange: taco_exchange
      routing-key: central
  kafka:
    bootstrap-servers: 0.0.0.0:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: cloudGroupId
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: org.might.sinaction.db.entity

taco:
  orders:
    page-size: 20


---
spring:
  config:
    activate:
      on-profile:
        development

  datasource:
    generate-unique-name: false
    name: tacocloud
    url: "jdbc:h2:mem:tacocloud"

logging:
  level:
    root: info
    org.springframework.security: info
    org.springframework.kafka: DEBUG