spring:
  application:
    name: business
  thymeleaf:
    cache: false
  profiles:
    active:
      development

taco:
  orders:
    page-size: 20


---
spring:
  config:
    activate:
      on-profile:
        development

  datasource:
    generate-unique-name: false
    name: tacocloud
    url: "jdbc:h2:mem:tacocloud"

logging:
  level:
    root: info
    org.springframework.security: info