version: "3.7"

services:
  postgres:
    container_name: postgres_container
    hostname: postgres_clean
    image: postgres:11.13
    environment:
      POSTGRES_PASSWORD: postgres
    privileged: true
    tty: true
    ports:
      - "5432:5432"
    expose:
      - "5432"

  rabbitmq:
    container_name: local_rabbit
    hostname: local_rabbit
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: vhost
    privileged: true
    tty: true
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"


  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:29092"

    ports:
      - 9999:8080
    links:
      - kafka

  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"

  cassandra:
    container_name: cassandra_container
    ports:
      - "9042:9042"
    image: cassandra:latest
