version: "3.7"

services:
  postgres:
    container_name: postgres_container
    hostname: postgres_clean
    image: postgres:11.13
    environment:
      POSTGRES_PASSWORD: postgres
    privileged: true
    tty: true
    ports:
      - "5432:5432"
    expose:
      - "5432"

  rabbitmq:
    container_name: local_rabbit
    hostname: local_rabbit
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: vhost
    privileged: true
    tty: true
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"

  cassandra:
    container_name: cassandra_container
    ports:
      - "9042:9042"
    image: cassandra:latest
